version: '3.9'

services:
  database:
    image: postgres
    container_name: databasepg
    restart: always
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test

